version: '3'
services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db   # Mount MongoDB data to the Host machine

  # Nginx Service
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html   # Mount Nginx html directory to the Host machine
      - ./nginx/config:/etc/nginx/conf.d     # Mount Nginx config directory to the Host machine

  # Express.js (FrontEnd) Service
  frontend:
    image: node:latest
    container_name: frontend
    working_dir: /usr/src/app
    command: npm start
    volumes:
      - ./frontend:/usr/src/app       # Mount frontend app directory to the Host machine
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
